#!/bin/sh
# K1C 2025 USB Camera Service

case "$1" in
  start)
    echo "Starting USB Camera..."
    PORT=8082
    BUILTIN_DEV="/dev/video0"
    V4L_DEVS=$(v4l2-ctl --list-devices | grep -A1 usb | sed 's/^[[:space:]]*//g' | grep '^/dev' | grep -v "^$BUILTIN_DEV$")
    if [ "x$V4L_DEVS" = "x" ]; then
      echo "Error: No third party USB camera found!"
      exit 1
    fi
    for V4L_DEV in $V4L_DEVS; do
      /opt/bin/mjpg_streamer -b -i "/opt/lib/mjpg-streamer/input_uvc.so -d $V4L_DEV -r 1280x720 -f 15" -o "/opt/lib/mjpg-streamer/output_http.so -p $PORT"
      PORT=`expr $PORT + 1`
    done
    ;;
  stop)
    echo "Stopping USB Camera..."
    PIDS=$(ps | grep '[m]jpg_streamer' | grep 'output_http.so -p 808[2-9]' | awk '{print $1}')
    [ -n "$PIDS" ] && kill $PIDS
    exit 0
    ;;
  restart|reload)
    "$0" stop
    sleep 1
    "$0" start
    ;;
  *)
    echo "Usage: /etc/init.d/S50usb_camera {start|stop|restart}"
    exit 1
esac

exit $?
